# Database
DATABASE_HOST:
DATABASE_USERNAME:
DATABASE_PASSWORD:
DATABASE_NAME:

# Server
SECRET_KEY_BASE:
SERVER_HOST:

# Google
GOOGLE_API_KEY:
GOOGLE_APPLICATION_CREDENTIALS:

# Sidekiq
SCHEDULE_FILE_PATH: "../sidekiq_scheduler.yml"
REDIS_URL:

# Sendgrid
SENDGRID_API_KEY:

SMTP_ADDRESS:
SMTP_PORT:
SMTP_DOMAIN:
SMTP_USER_NAME:

DEFAULT_EMAIL_FROM:
DEFAULT_REPLY_TO:

DEFAULT_TEMPLATE_ID:

# Kafka
KAFKA_BROKERS:
KAFKA_CLIENT_ID:

# CSV
FILE_PATH:

# Sentry
SENTRY_DSN:
SENTRY_ENABLED_ENVIRONMENTS:
SENTRY_TRACES_SAMPLER_RATE:
