default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  socket: <%= ENV.fetch("DATABASE_SOCKET", "/var/run/mysqld/mysqld.sock") %>

development:
  <<: *default

test:
  <<: *default
  database: demo_test

staging:
  <<: *default

production:
  <<: *default
