default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "Aa@123456") %>
  database: <%= ENV.fetch("DATABASE_NAME", App::NAME) %>
  socket: <%= ENV.fetch("DATABASE_SOCKET", "/tmp/mysql.sock") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>

development:
  <<: *default

test:
  <<: *default
  database: demo_test

staging:
  <<: *default

production:
  <<: *default
